[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "kubemind-config"
version = "0.3.3"
description = "Centralized environment & config file resolution for KubeMind microservices"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools.packages.find]
where = ["."]
include = ["kubemind_config*"]
