apiVersion: v1
kind: Secret
metadata:
  name: tricore-secrets
  namespace: tricore
type: Opaque
stringData:
  postgres-password: "tricore"
  NEXTAUTH_SECRET: "change-me-to-random-32-byte-string"
  GITHUB_CLIENT_ID: ""
  GITHUB_CLIENT_SECRET: ""
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
